import { Product } from "~/global/types/product";

export const allProductsMock : Product[] = [
    {
        "id": 12345,
        "name": "MCAP Value-Flex Variable Special",
        "family": "VALUE_FLEX",
        "type": "VARIABLE",
        "term": "5_YEAR",
        "insurable": true,
        "insurance": "CONVENTIONAL",
        "prepaymentOption": "STANDARD",
        "restrictionsOption": "SOME_RESTRICTIONS",
        "restrictions": "MCAP_VALUE_FLEX_RESTRICTIONS",
        "fixedPenaltySpread": "SMALL_PENALTY",
        "helocOption": "HELOC_WITHOUT",
        "helocDelta": 0,
        "lenderName": "nesto",
        "lenderType": "MONOLINE",
        "rateHold": "120_DAYS",
        "rate": 1.45,
        "ratePrimeVariance": -1.2,
        "bestRate": 1.25,
        "created": "2021-06-07T13:30:38Z",
        "updated": "2021-06-07T13:47:09Z"
    },
    {
        "id": 12346,
        "name": "Standard",
        "family": "VALUE_FLEX",
        "type": "VARIABLE",
        "term": "5_YEAR",
        "insurable": false,
        "insurance": "CONVENTIONAL",
        "prepaymentOption": "HELOC",
        "restrictionsOption": "NO_RESTRICTIONS",
        "restrictions": "NO_NOTABLE_RESTRICTIONS",
        "fixedPenaltySpread": "BANK_PENALTY",
        "helocOption": "HELOC_WITHOUT",
        "helocDelta": 0,
        "lenderName": "nesto",
        "lenderType": "BIG_BANK",
        "rateHold": "120_DAYS",
        "rate": 1.55,
        "ratePrimeVariance": -1.15,
        "bestRate": 1.45,
        "created": "2021-06-07T13:30:38Z",
        "updated": "2021-06-07T13:47:11Z"
    },
    {
        "id": 12347,
        "name": "MCAP Value-Flex Fixed Special",
        "family": "VALUE_FLEX",
        "type": "FIXED",
        "term": "5_YEAR",
        "insurable": true,
        "insurance": "CONVENTIONAL",
        "prepaymentOption": "STANDARD",
        "restrictionsOption": "SOME_RESTRICTIONS",
        "restrictions": "MCAP_VALUE_FLEX_RESTRICTIONS",
        "fixedPenaltySpread": "SMALL_PENALTY",
        "helocOption": "HELOC_WITHOUT",
        "helocDelta": 0,
        "lenderName": "nesto",
        "lenderType": "MONOLINE",
        "rateHold": "90_DAYS",
        "rate": 2.24,
        "ratePrimeVariance": 0,
        "bestRate": 2.04,
        "created": "2021-06-07T13:34:14Z",
        "updated": "2021-06-07T13:47:33Z"
    },
    {
        "id": 12348,
        "name": "Standard (Quick Close Special)",
        "family": "VALUE_FLEX",
        "type": "FIXED",
        "term": "5_YEAR",
        "insurable": true,
        "insurance": "CONVENTIONAL",
        "prepaymentOption": "STANDARD",
        "restrictionsOption": "NO_RESTRICTIONS",
        "restrictions": "NO_NOTABLE_RESTRICTIONS",
        "fixedPenaltySpread": "SMALL_PENALTY",
        "helocOption": "HELOC_WITHOUT",
        "helocDelta": 0,
        "lenderName": "nesto",
        "lenderType": "MONOLINE",
        "rateHold": "60_DAYS",
        "rate": 2.24,
        "ratePrimeVariance": 0,
        "bestRate": 2.14,
        "created": "2021-06-07T13:34:14Z",
        "updated": "2021-06-07T13:47:32Z"
    },
    {
        "id": 12310,
        "name": "Standard",
        "family": "VALUE_FLEX",
        "type": "FIXED",
        "term": "5_YEAR",
        "insurable": true,
        "insurance": "CONVENTIONAL",
        "prepaymentOption": "STANDARD",
        "restrictionsOption": "NO_RESTRICTIONS",
        "restrictions": "NO_NOTABLE_RESTRICTIONS",
        "fixedPenaltySpread": "SMALL_PENALTY",
        "helocOption": "HELOC_WITHOUT",
        "helocDelta": 0,
        "lenderName": "nesto",
        "lenderType": "MONOLINE",
        "rateHold": "120_DAYS",
        "rate": 2.34,
        "ratePrimeVariance": 0,
        "bestRate": 2.24,
        "created": "2021-06-07T13:34:14Z",
        "updated": "2021-06-07T13:47:35Z"
    },
    {
        "id": 12311,
        "name": "Standard Special",
        "family": "VALUE_FLEX",
        "type": "FIXED",
        "term": "5_YEAR",
        "insurable": false,
        "insurance": "CONVENTIONAL",
        "prepaymentOption": "STANDARD",
        "restrictionsOption": "NO_RESTRICTIONS",
        "restrictions": "NO_NOTABLE_RESTRICTIONS",
        "fixedPenaltySpread": "SMALL_PENALTY",
        "helocOption": "HELOC_WITHOUT",
        "helocDelta": 0,
        "lenderName": "nesto",
        "lenderType": "MONOLINE",
        "rateHold": "120_DAYS",
        "rate": 2.34,
        "ratePrimeVariance": 0,
        "bestRate": 2.24,
        "created": "2021-06-07T13:34:14Z",
        "updated": "2021-06-07T13:47:35Z"
    }
];

export const multipleProductsWithBestFixedRateMock: Product[] = [
    {
        "id": 12311,
        "name": "Standard Special",
        "family": "VALUE_FLEX",
        "type": "FIXED",
        "term": "5_YEAR",
        "insurable": false,
        "insurance": "CONVENTIONAL",
        "prepaymentOption": "STANDARD",
        "restrictionsOption": "NO_RESTRICTIONS",
        "restrictions": "NO_NOTABLE_RESTRICTIONS",
        "fixedPenaltySpread": "SMALL_PENALTY",
        "helocOption": "HELOC_WITHOUT",
        "helocDelta": 0,
        "lenderName": "nesto",
        "lenderType": "MONOLINE",
        "rateHold": "120_DAYS",
        "rate": 2.34,
        "ratePrimeVariance": 0,
        "bestRate": 2.4,
        "created": "2021-06-07T13:34:14Z",
        "updated": "2021-06-07T13:47:35Z"
    },
    {
        "id": 12312,
        "name": "Standard Special 1",
        "family": "VALUE_FLEX",
        "type": "FIXED",
        "term": "5_YEAR",
        "insurable": false,
        "insurance": "CONVENTIONAL",
        "prepaymentOption": "STANDARD",
        "restrictionsOption": "NO_RESTRICTIONS",
        "restrictions": "NO_NOTABLE_RESTRICTIONS",
        "fixedPenaltySpread": "SMALL_PENALTY",
        "helocOption": "HELOC_WITHOUT",
        "helocDelta": 0,
        "lenderName": "RBC",
        "lenderType": "MONOLINE",
        "rateHold": "120_DAYS",
        "rate": 2.34,
        "ratePrimeVariance": 0,
        "bestRate": 2.24,
        "created": "2021-06-07T13:34:14Z",
        "updated": "2021-06-07T13:47:35Z"
    },
    {
        "id": 12313,
        "name": "Standard Special",
        "family": "VALUE_FLEX",
        "type": "FIXED",
        "term": "5_YEAR",
        "insurable": false,
        "insurance": "CONVENTIONAL",
        "prepaymentOption": "STANDARD",
        "restrictionsOption": "NO_RESTRICTIONS",
        "restrictions": "NO_NOTABLE_RESTRICTIONS",
        "fixedPenaltySpread": "SMALL_PENALTY",
        "helocOption": "HELOC_WITHOUT",
        "helocDelta": 0,
        "lenderName": "CIBC",
        "lenderType": "MONOLINE",
        "rateHold": "120_DAYS",
        "rate": 2.34,
        "ratePrimeVariance": 0,
        "bestRate": 2.24,
        "created": "2021-06-07T13:34:14Z",
        "updated": "2021-06-07T13:47:35Z"
    }
]